#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int timeStepMs = 50;
int error = 0;
int dt = 0;
int goal = 1000;
int integral = 0;
int kP = 5;
int kI = 0.1;

// Should figure how this works
int integrate(){

}


void set(int voltage){
	motor[leftMotor] = voltage;
	motor[rightMotor] = voltage;
}

task main(){
	datalogClear();

	while(true){
		datalogDataGroupStart();


			error = goal - getMotorEncoder(leftMotor);
			integral = integral + error * timeStepMs;
			datalogAddValue(2, error);
			datalogAddValue(3, integral);

			int voltage = kP * error + kI * integral;
			set(voltage);

		datalogDataGroupEnd();
			while(time1[timer1] <= timeStepMs){
				wait1Msec(1);
			}
			clearTimer(timer1);
	}

}
