#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move(float dist, float speed);
void turn(float amount, float speed);

int rightPos;

int viewOfLeftDistTraveled;

task main()
{
  wait1Msec(500);

  resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);

  /*
  while(getMotorEncoder(rightMotor) < 1800)
  {
    motor[rightMotor] = 63;
    motor[leftMotor] = 63;
  }

  motor[rightMotor] = 0;
  motor[leftMotor] = 0;*/
  int dist = 1200;

  move(90, 50);
  //move(dist, -120);
  //move(dist*2, 120);
  turn(360, 20);
  //move(dist*2, -120);
  //move(dist*3, 120);
  //move(dist*3, -120);
}

void move(float dist, float speed){
	float leftStartPos = abs(SensorValue[leftEncoder]);
	float rightStartPos = abs(SensorValue[rightEncoder]);

	motor[leftMotor] = speed;
	motor[rightMotor] = speed;

	float leftDistTraveled = abs(abs(SensorValue[rightEncoder]) - rightStartPos);
	float rightDistTraveled = abs(abs(SensorValue[leftEncoder]) - leftStartPos);

	while (leftDistTraveled < dist && rightDistTraveled < dist){
		leftDistTraveled = abs(abs(SensorValue[rightEncoder]) - rightStartPos);
		viewOfLeftDistTraveled = leftDistTraveled;
		rightDistTraveled = abs(abs(SensorValue[leftEncoder]) - leftStartPos);
		rightPos = SensorValue[rightEncoder];
		wait1Msec(5);
	}
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}

void turn(float amount, float speed){
	float leftStartPos = abs(SensorValue[leftEncoder]);
	float rightStartPos = abs(SensorValue[rightEncoder]);

	motor[leftMotor] = speed;
	motor[rightMotor] = speed * -1;

	float leftDistTraveled = abs(abs(SensorValue[rightEncoder]) - rightStartPos);
	float rightDistTraveled = abs(abs(SensorValue[leftEncoder]) - leftStartPos);

	while (leftDistTraveled < amount && rightDistTraveled < amount){
		leftDistTraveled = abs(abs(SensorValue[rightEncoder]) - rightStartPos);
		viewOfLeftDistTraveled = leftDistTraveled;
		rightDistTraveled = abs(abs(SensorValue[leftEncoder]) - leftStartPos);
		rightPos = SensorValue[rightEncoder];
		wait1Msec(5);
	}
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
