#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "simple_encoder_movement.h"

task main()
{
  wait1Msec(500);

  resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);

  int dist = 1400;
  int speed = 100;

  move(dist, speed);
}
