#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "simple_encoder_movement.h"

task main()
{
  wait1Msec(500);

  resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);

  /*
  while(getMotorEncoder(rightMotor) < 1800)
  {
    motor[rightMotor] = 63;
    motor[leftMotor] = 63;
  }

  motor[rightMotor] = 0;
  motor[leftMotor] = 0;*/
  int dist = 1200;

  move(90, 50);
  //move(dist, -120);
  //move(dist*2, 120);
  resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);
  turn(360, 20);
  //move(dist*2, -120);
  //move(dist*3, 120);
  //move(dist*3, -120);
}
